#+OPTIONS: toc:nil
* Summary
:PROPERTIES:
:EXPORT_FILE_NAME: SUMMARY.md
:END:

#+BEGIN_SRC emacs-lisp :exports results :results value org replace
(org-build-gitbook-toc)
#+END_SRC

- [[file:README.md#the-buttplug-sex-toy-control-standard][The Buttplug Sex Toy Control Standard]]
  - [[file:README.md#the-need-for-a-sex-toy-control-standard][The Need for a Sex Toy Control Standard]]
  - [[file:README.md#generalized-control][Generalized Control]]
  - [[file:README.md#comparisons-to-existing-software][Comparisons to Existing Software]]
  - [[file:README.md#why-is-it-called-buttplug][Why is it called Buttplug?]]
- [[file:architecture.md#architecture][Architecture]]
  - [[file:architecture.md#implementation-types][Implementation Types]]
    - [[file:architecture.md#libraries][Libraries]]
    - [[file:architecture.md#servers][Servers]]
    - [[file:architecture.md#applications-aka-clients][Applications (aka Clients)]]
  - [[file:architecture.md#protocol][Protocol]]
  - [[file:architecture.md#stages][Stages]]
    - [[file:architecture.md#identification][Identification]]
    - [[file:architecture.md#enumeration][Enumeration]]
    - [[file:architecture.md#consummation][Consummation]]
- [[file:usages.md#usage-examples][Usage Examples]]
  - [[file:usages.md#library-embedded-in-a-video-game][Library Embedded in a Video Game]]
  - [[file:usages.md#web-based-hardware-synced-movie-player][Web Based Hardware Synced Movie Player]]
- [[file:messages.md#messages][Messages]]
  - [[file:messages.md#basic-message-structure][Basic Message Structure]]
  - [[file:messages.md#messages][Messages]]
    - [[file:messages.md#ok][Ok]]

* Introduction
:PROPERTIES:
:EXPORT_FILE_NAME: README.md
:END:
** The Buttplug Sex Toy Control Standard

Buttplug is a quasi-standard set of technologies and protocols to
allow developers to write software that controls an array of sex toys
in a semi-future-proof way.

*** The Need for a Sex Toy Control Standard

If a user wants to access a computer controlled sex toy in a way not
supported by the original manufacturer, the requirement list to is not
trivial. There are some major hurdles between obtaining a sex toy and
having DIY control of it:

- Experience in the operating system the user will want to access the
  sex toy from, including capabilities and programming interfaces to
  work with the connection medium (serial/usb/bluetooth/etc)
- Experience using a programming language that allows the user access
  to hardware via the operation system.
- Knowledge of the communications protocol the sex toy uses. This is
  rarely, if ever, publicly documented information.

The Buttplug Sex Toy Control Standard seeks to lower these bars as
much as possible.

- By proposing a standard that can be implemented in a cross-platform
  way, software based on the Buttplug Standard can reduce the amount
  of knowledge required to access hardware from a certain operating
  system or platform. Using technologies like Cordova or Xamarin to
  build software that implements Buttplug means that access could
  happen via desktop or mobile platforms.
- By standardizing the methods that can be used to talk to these toys,
  implementations of the standard can happen in multiple languages and
  still interact with each other. This opens development opportunities
  to multiple communities and ecosystems.
- Assuming some sort of widespread adoption happens, this could drive
  the commercial market to build toys with the Buttplug Standard in
  mind, or even to use it directly. Until that point, the portion of
  the community familiar with reverse engineering can help open sex
  toy access to those who are interested in controlling the toys.

*** Generalized Control

One of the windmills Buttplug tilts at is the idea of "generalized
control". Simply put, is it viable to drive completely different sex
toys from the same control signal? In some cases, this is simple. In
others, it may be impossible.

Starting with the simple case, let's say a user has two sex toys,
called Toy A and Toy B:

- Each toy is made by a different manufacturer. 
- One toy uses Bluetooth to talk to the computer, the other uses USB.
- Both of these toys have vibration functionality.

The user has a particular function they would like to implement in a
software application, which would utilize the vibration function of
both toys.

Without Buttplug, this would require knowing how to talk to both USB
and Bluetooth, and also knowing how each of these toys communicates
with the computer in order to control vibration levels. They would
then have to add both of these to their application.

With Buttplug, Server implementations are expected to take care of the
different manufacturer and hardware communication requirements.
However, if there were only ways to communicate with specific
hardware, the application they were making would have to provide
separate logic paths to cover either toy instance.

This is where the idea of "generalized haptics" comes in. Instead of
either a "Toy A" or "Toy B" command to the server, the user can just
send a "Vibrate" command to the server, along with the identifier for
which toy they wanted to use. Not only that, their software would work
with any toy (including toys they do not own/have tested with) that
could translate the "Vibrate" command.

Now, the not so simple case.

Let's add Toy C, an electrostimulation unit. To use Toy C with the
same application as Toy A and Toy B, the Vibrate command has to be
translated into some facsimile that is valid for estim. While this is
most likely not tractable for a global solution, the goal of Buttplug
is to make explorations of ideas like this accessible and easy to play
with.

*** Comparisons to Existing Software

It's somewhat difficult to point to a real world counterpart for the
Buttplug Standard. While companies like [[http://twitter.com/frixionme][Frixion]] and [[http://feelme.com][FeelMe]] have
created systems for controlling different sex toys, neither of those
is open source, so it's hard to point at them as examples.

The closest existing projects are those which reinterpret or
generalize control schemes. Projects like:

- [[http://andersmalmgren.github.io/FreePIE/][FreePIE]]
- [[https://osculator.net/][OSCulator]]
- [[https://github.com/vrpn/vrpn/wiki][VRPN]]
- [[http://vjoystick.sourceforge.net/site/][vJoy]]

All of these programs take input from various devices and translate
them as some other kind of input, or aggregate them to make systems
easier to use. The Buttplug Standard aims to define programs which do
something similar. Applications referred to as "Buttplug Server"
implementations will often look quite similar to these programs.

*** Why is it called Buttplug?

It probably seems silly to call a sex toy control standard "Buttplug". 

That's because it is.

I could probably call this project something neutral like STCS, but
I've been referring to computer controlled sex toys as "Internet
Buttplugs" for years, and that's what influenced the name of this
project. It's hard to pick terms for these products.

- "Sex toy" is weighed down by the word "toy". This is part of the
  reason the academic and tech community is flocking toward "sex
  robot" even when discussing technology that would've been called a
  sex toy a decade ago.
- "Sex robot" has way too many connotations, be it Cherry 2000 or
  robotics academics writing media-friendly PhD theses.
- "Adult novelty" just sounds stale and corporate. You buy adult
  novelties in bulk from warehouses. You go to adult novelty
  conventions.
- "Marital aide" No.

I ended up with "Internet Buttplug" because everyone has a butt, and
buttplug is a fun word to say. It's inclusive and it's humorous. I
admit that it may confuse people when they're wondering why they're
using something called Buttplug to control their fucking machine or
robotic onahole or who knows what else. 

One of the hardest problems in Computer Science is naming things. I
just stopped trying to name the thing and selected a name and here we
are. Much like the other hard problems in Computer Science, I fully
expect this to come back to bite me in the ass at some point.

* Architecture
:PROPERTIES:
:EXPORT_FILE_NAME: architecture.md
:END:
** Architecture
*** Implementation Types

The Buttplug Standard can be implemented in different ways. This
section covers the terms used throughout this document. 

**** Libraries

Implementing the standard as a library for a certain programming
language allows developers to either build servers on top of the
library in that language, or to integrate the library into their
applications that also use that language (or FFI/bindings to that
language). For instance, the C# implementation of the Buttplug
Standard can be used with a WebSocket implementation on top of it to
be a server that other applications can talk to. It could also be
compiled into a Unity game so that the communication exists only in
the executable itself.

**** Servers

As mentioned above, servers are a thin layer on top of a library that
allow other applications to access hardware managed by the server. For
instance, a Web Application may not have the capability to talk to
hardware by itself, but can connect with a Buttplug Server
implementation via HTTP, WebSockets, or other standardized protocols.
Programs like Max/MSP and Pd could communicate with a Buttplug Server
implementation via OSC.

**** Applications (aka Clients)

Applications, or clients, refer to programs that in some way interact
with a server to perform some sort of job for the user. A few ideas
for applications:

- A movie player that sends synchronization commands while playing an
  encoded video.
- A music player that syncs sex toys with the BPM of the current
  track.
- A video game that somehow involves sex toy interaction

All of these would need to talk to a Buttplug server to establish
which devices to use, then communicate with those devices.

*** Protocol

The Buttplug Standard defines a message based protocol between a
client and a server. Note that the use of client and server here does
not explicitly denote network connection. These terms are used as a
generic way to denote different communication endpoints.

Client are expected to request information from the server about
devices that are connected, and to send information to those devices
via the server. Servers will handle device enumeration, connection
management, and failure recoveries (for instance, stopping all
connected devices on client disconnect).

While serialization formats are not yet standardized, current
references implementations of the Standard use JSON for serialization.
More information on this is available in the Messages section.

*** Stages

Buttplug sessions consist of 3 stages. While these stages need not be
discrete, due to the way Buttplug will likely be used, they will
usually end up being so. Applications may hide or combine some of the
stages depending on requirements.

**** Identification

During the identification stage, a client will establish connection
with the server, and send over its identifying information. The server
may trigger some sort of UI event at this point to ask if the user
will allow the client to connect and interact.

**** Enumeration

After the client/server connection is set up, device enumeration can
begin. The client can ask the server to scan for devices on various
busses or media (serial, usb, bluetooth, network, etc), and return a
list of devices it can communicate with.

**** Consummation

Once devices are found and selected, we can assume the user will begin
interacting with connected devices. At this point, the client will
mostly be sending and receiving device commands. It can usually (but
not always) be assumed that continued enumeration may not be possible
due to the context of situations that Buttplug software will be used
in.

* Usage Examples
:PROPERTIES:
:EXPORT_FILE_NAME: usages.md
:END:
** Usage Examples

To concretize this otherwise theoretical discussion, here are some
in-depth examples of how Buttplug implementations could be architected
in the wild.

*** Library Embedded in a Video Game

First off, a simple example using a single program with an embedded
library.

A developer would like to ship a game on Windows, using the Unity
Engine, that has some sort of interaction with sex toys. Since we want
concrete examples here, let's say it's a version of Tetris that
increases vibrator speeds based on how many lines have been made by
the player.

Due to the nature of games, the developer would want it to have as
little impact on performance as possible. They would also want the
server to exist in the game executable, so that it can be shipped as a
single package.

In this case, the developer could use a Buttplug library
implementation, possibly the C# reference library since this is Unity.
Inside the game, device connection configuration could be part of the
game settings menus, allow devices to be automatically reconnected on
game startup. To communicate with the embedded server during gameplay,
C# message objects could be sent to a thread for handling, so that IO
timing doesn't lag the game loop.

One of the important things lost by direct library integration is the
ability to support new hardware. If a game is simple sending a generic
"Vibrate" command, it is basically future-proofed for all toys that
will support that command in the future, assuming it has a way to send
that message to something that supports the new hardware. If a library
is compiled into the game, there would be no way to add this hardware
support though. There are multiple solutions to this issue, but those
are outside the scope of this example.

*** Web Based Hardware Synced Movie Player

Now, a far more difficult scenario. This example tries to build a
shotgun to hit as many platforms as possible with as little code as
possible.

The goal is to build a web based movie player, that will load movies
with synchronization files, and play them back while controlling
hardware. We will assume we are working with browsers that give us a
minimum of HTML5 Video playback and WebSockets. We want our
application to work on as many platforms as possible. The movie player
should be capable of talking to as many devices as possible on as many
platforms as possible, including desktop and mobile. The main focus
for toy support will be Bluetooth LE toys, with all others considered
nice to have.

At this point, we have to take operating system and browser
capabilities into account. 

Operating Systems that have BLE:

- Windows 10 (Version 15063 and later)
- macOS (10.6 or later)
- Linux (with Bluez 5.22 or later)
- Android (version 5 or later)
- iOS (LE support versions unknown)
- ChromeOS (LE support versions unknown)

Web Browsers with WebBluetooth:

- Chrome 56 on Mac, Linux, Android, ChromeOS

This means that if we implement a Buttplug Server in Javascript using
WebBluetooth to access BLE devices, we can target the Chrome web
browser and support 2 major desktop platforms, 1 mobile platform, and
whatever ChromeOS is. We can also ship this server implementation as
part of the movie player application, meaning it will all work as a
unit, similar to the game example above. Future-proofing could
feasibly happen with CDN hosting of the library via semantic
versioning adherence.

Unfortunately, that leaves out Windows and iOS. To maximize ROI on
custom support implementation, we're more likely to see more users via
Windows than iOS, so we'll concentrate on Windows first.

To talk to Bluetooth LE on Windows 10 requires access to UWP APIs, so
following a "When In Rome" philosophy, we can implement a Buttplug
Library in C#. On top of this we can build a server exposed via
WebSockets, to let the browser application talk to the native server.
A native implementation gives us the extra win of USB and Serial, at
least, until WebUSB sex toys become a thing.

Going back to the web application itself, this now means the client
side will need to connect to one of two different styles of servers.
We can use User Agent Detection in the browser to let us know which OS
we're on, and then either select the WebBluetooth path or native
Windows Websocket path. 

To hit iOS, we now have the option of going via a Xamarin based C#
app, or a Node.js/Cordova app. There will be some custom
implementation on either side, but most of the heavy lifting will have
been done before this.

An aside for those wondering why this wasn't all done in Node.js. At
the time of this writing, node.js bindings to UWP APIs do exist, but
were still iffy at best. Not only that, distributing a native
application like the Buttplug Server would've required wrapping in
something like nw.js, massively inflating distributable size.
Implementing a C# version of the Buttplug Library also gives us a
platform into Unity integration.
* Messages
:PROPERTIES:
:EXPORT_FILE_NAME: messages.md
:END:
** Messages
*** Basic Message Structure
*** Messages
**** Ok

The Ok message is a message.
