mod lovense_connect_service_device_impl;
mod lovense_connect_service_comm_manager;
pub use lovense_connect_service_device_impl::LovenseServiceDeviceImpl;
pub use lovense_connect_service_comm_manager::{LovenseConnectServiceCommunicationManager, LovenseConnectServiceCommunicationManagerBuilder};